#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export PYTHONUNBUFFERED=1
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"

export SERVING_HOST="${SERVING_HOST:-127.0.0.1}"
export SERVING_PORT="${SERVING_PORT:-8080}"
export SERVING_MODEL_ROOT="${SERVING_MODEL_ROOT:-$ROOT_DIR/models}"
export SERVING_CONFIG_PATH="${SERVING_CONFIG_PATH:-$ROOT_DIR/config/active_models.json}"
export SERVING_UPLOAD_TMP_ROOT="${SERVING_UPLOAD_TMP_ROOT:-$ROOT_DIR/tmp/uploads}"
export SERVING_OBSERVABILITY_RING_PATH="${SERVING_OBSERVABILITY_RING_PATH:-$ROOT_DIR/logs/observability.ring}"
export SERVING_OBSERVABILITY_RING_MB="${SERVING_OBSERVABILITY_RING_MB:-128}"
export SERVING_RESOURCE_SAMPLING_INTERVAL_SEC="${SERVING_RESOURCE_SAMPLING_INTERVAL_SEC:-0.5}"
export SERVING_CPU_BUDGET="${SERVING_CPU_BUDGET:-4}"

mkdir -p "$ROOT_DIR/models" "$ROOT_DIR/config" "$ROOT_DIR/logs" "$ROOT_DIR/tmp/uploads"
